from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def _slugify_name(raw: str) -> str:
    value = raw.strip().lower()
    value = re.sub(r"[^a-z0-9_]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")
    if not value:
        raise ValueError("Name must include at least one alphanumeric character.")
    if not value[0].isalpha():
        value = f"task_{value}"
    return value


def _camel_from_slug(slug: str) -> str:
    return "".join(part.capitalize() for part in slug.split("_") if part) + "Task"


def _module_path_for_python_file(path: Path) -> str:
    stem = path.with_suffix("")
    try:
        rel = stem.resolve().relative_to(Path.cwd().resolve())
        return ".".join(rel.parts)
    except Exception:
        return stem.name


def cmd_init_external_task(args: argparse.Namespace) -> int:
    try:
        slug = _slugify_name(args.name)
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 2

    out_dir = Path(args.out_dir) if args.out_dir else Path("examples") / f"{slug}_demo"
    if out_dir.exists() and any(out_dir.iterdir()) and not args.force:
        print(
            f"Refusing to overwrite non-empty directory: {out_dir}. "
            "Use --force or choose a new --out-dir.",
            file=sys.stderr,
        )
        return 2

    out_dir.mkdir(parents=True, exist_ok=True)
    class_name = args.class_name.strip() if isinstance(args.class_name, str) and args.class_name.strip() else _camel_from_slug(slug)
    task_file = out_dir / f"{slug}_task.py"
    spec_file = out_dir / f"spec_{slug}.yml"
    module_path = _module_path_for_python_file(task_file)

    task_source = f'''from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from qiskit import QuantumCircuit

from claimstab.methods.spec import MethodSpec
from claimstab.tasks.base import BuiltWorkflow
from claimstab.tasks.instances import ProblemInstance


@dataclass(frozen=True)
class {class_name}Payload:
    num_qubits: int


class {class_name}:
    """External task plugin starter generated by ClaimStab."""

    name = "{slug}"

    def __init__(self, num_qubits: int = 6, num_instances: int = 3) -> None:
        self.num_qubits = int(num_qubits)
        self.num_instances = int(num_instances)

    def instances(self, suite: str) -> list[ProblemInstance]:
        return [
            ProblemInstance(
                instance_id=f"{slug}_{{suite}}_{{i}}",
                payload={class_name}Payload(num_qubits=self.num_qubits),
            )
            for i in range(self.num_instances)
        ]

    def build(self, instance: ProblemInstance, method: MethodSpec) -> BuiltWorkflow:
        payload = instance.payload
        n = int(getattr(payload, "num_qubits", self.num_qubits))
        qc = QuantumCircuit(n)

        if method.kind == "method_a":
            qc.h(range(n))
        elif method.kind == "method_b":
            pass
        else:
            raise ValueError(f"Unsupported method kind: {{method.kind}}")

        qc.measure_all()

        def metric_fn(counts: dict[str, int]) -> float:
            total = sum(counts.values())
            if total == 0:
                return 0.0
            ones = 0.0
            for bitstring, c in counts.items():
                ones += (c / total) * bitstring.count("1")
            return ones / n

        return BuiltWorkflow(circuit=qc, metric_fn=metric_fn)
'''

    spec_source = f'''spec_version: 1
pipeline: main
meta:
  name: {slug}_demo
  description: External task starter generated by claimstab init-external-task

task:
  kind: external
  entrypoint: {module_path}:{class_name}
  suite: toy
  params:
    num_qubits: 6
    num_instances: 3

methods:
  - name: MethodA
    kind: method_a
  - name: MethodB
    kind: method_b

claims:
  - type: ranking
    method_a: MethodA
    method_b: MethodB
    deltas: [0.0, 0.05]

perturbations:
  presets: [sampling_only]

sampling:
  mode: random_k
  sample_size: 12
  seed: 7
  include_baseline: true

decision_rule:
  threshold: 0.95
  confidence_level: 0.95

backend:
  engine: basic
  noise_model: none
'''

    task_file.write_text(task_source, encoding="utf-8")
    spec_file.write_text(spec_source, encoding="utf-8")

    print(f"Generated starter in: {out_dir}")
    print(f"- Task plugin: {task_file}")
    print(f"- Spec: {spec_file}")
    print("Next steps:")
    print(f"1) claimstab validate-spec --spec {spec_file}")
    print(f"2) claimstab run --spec {spec_file} --out-dir output/{slug} --report")
    print(f"3) claimstab publish-result --run-dir output/{slug} --atlas-root atlas --contributor your_name")
    return 0
